// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR8XAt79u9CUMU2dqE1JmZ1e9djWdpcr0',
    appId: '1:732010681355:web:c8a465945f080c248e230e',
    messagingSenderId: '732010681355',
    projectId: 'cicd4-65399',
    authDomain: 'cicd4-65399.firebaseapp.com',
    storageBucket: 'cicd4-65399.firebasestorage.app',
    measurementId: 'G-2L9DDWHK1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnnu0eaKAOxIJQ5MGqTKrfO8VsQsmE7Dg',
    appId: '1:732010681355:android:72a5097a02f3f37c8e230e',
    messagingSenderId: '732010681355',
    projectId: 'cicd4-65399',
    storageBucket: 'cicd4-65399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_v8SB7KzKWTH1vwsISYVao5OMcLETWZA',
    appId: '1:732010681355:ios:a85245d98a813d748e230e',
    messagingSenderId: '732010681355',
    projectId: 'cicd4-65399',
    storageBucket: 'cicd4-65399.firebasestorage.app',
    iosBundleId: 'com.example.cicdMoc4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_v8SB7KzKWTH1vwsISYVao5OMcLETWZA',
    appId: '1:732010681355:ios:a85245d98a813d748e230e',
    messagingSenderId: '732010681355',
    projectId: 'cicd4-65399',
    storageBucket: 'cicd4-65399.firebasestorage.app',
    iosBundleId: 'com.example.cicdMoc4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR8XAt79u9CUMU2dqE1JmZ1e9djWdpcr0',
    appId: '1:732010681355:web:8bfeaf59298999338e230e',
    messagingSenderId: '732010681355',
    projectId: 'cicd4-65399',
    authDomain: 'cicd4-65399.firebaseapp.com',
    storageBucket: 'cicd4-65399.firebasestorage.app',
    measurementId: 'G-M2V4K170NY',
  );

}